
# apiVersion: v1
# kind: Service
# metadata:
#   name: oms-backend-service
# spec:
#   selector:
#     app: oms-backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
#       nodePort: 30001
#   type: LoadBalancer


apiVersion: v1
kind: Service
metadata:
  name: oms-backend-service
spec:
  selector:
    app: oms-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
